Enh: properly sign everything

diff --git a/fedora-22/inside/build-package b/fedora-22/inside/build-package
--- a/fedora-22/inside/build-package
+++ b/fedora-22/inside/build-package
@@ -1,7 +1,11 @@
 #!/bin/bash
 set -e
-#MAJOR="1"
-#MINOR="0"
+gpg --import /sign.key
+[[ $(gpg --list-secret-keys) =~ uid(.*) ]]
+KEYNAME="${BASH_REMATCH[1]}"
+[ -n "${KEYNAME}" ] || { echo "could not find key for signing purpose"; exit 1; }
+echo -e "%_gpg_name ${KEYNAME}\n%_signature gpg" > ${HOME}/.rpmmacros
+
 cd /out
 fpm -t rpm -s dir -n rake-standalone-${MAJOR} --version "${MAJOR}.${MINOR}" --iteration ${BUILD_NUMBER} --after-install /inside/after-install --before-remove /inside/before-remove --provides rake-standalone -C / opt
 chown -R --reference /inside/build-package .
